name: Capacities
title: Capacities
url: https://script1000.github.io/capacities_Beta/

show_dir_listing: true


source: .
destination: .
collections_dir: .
plugins_dir: assets/plugins
layouts_dir: _layouts
data_dir: _data
includes_dir: _includes

plugins:
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-commonmark-ghpages
  - jekyll-gist
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
  
